CREATE DATABASE "TISI"
TEMPLATE = TEMPLATE0
ENCODING 'UTF8'
CONNECTION LIMIT -1;

CREATE TABLE TB_EMPRESA(
	ID_EMPRESA SERIAL,
	RAZAO_SOCIAL VARCHAR(60),
	NOME_FANTASIA VARCHAR(60),
	CNPJ VARCHAR(18),
	EMAIL VARCHAR(40),
	SENHA VARCHAR(50),
	TELEFONE VARCHAR(20),
	RUA VARCHAR(40),
	NUMERO INTEGER,
	BAIRRO VARCHAR(40),
	CEP VARCHAR(15),
	CIDADE VARCHAR(60),
	ESTADO VARCHAR(40),
	FG_ATIVO INTEGER,
CONSTRAINT PK_TB_EMPRESA_ID_EMPRESA PRIMARY KEY(ID_EMPRESA));
	
	

CREATE TABLE TB_CLIENTE_FISICO(
	ID_CLIENTE SERIAL,
	NOME VARCHAR(60),
	SOBRENOME VARCHAR(60),
	CPF VARCHAR(15),
	DT_NASCIMENTO DATE,
	EMAIL VARCHAR(40),
	TELEFONE VARCHAR(20),
	RUA VARCHAR(40),
	NUMERO INTEGER,
	BAIRRO VARCHAR(40),
	CEP VARCHAR(15),
	CIDADE VARCHAR(60),
	ESTADO VARCHAR(40),
	ID_EMPRESA INTEGER,
	FG_ATIVO INTEGER,
CONSTRAINT PK_TB_CLIENTE_FISICO_ID_CLIENTE PRIMARY KEY(ID_CLIENTE));	
	


CREATE TABLE TB_CLIENTE_JURIDICO(
	ID_CLIENTE SERIAL,
	NOME_FANTASIA VARCHAR(60),
	RAZAO_SOCIAL VARCHAR(30),
	CNPJ VARCHAR(20),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(20),
	RUA VARCHAR(40),
	NUMERO INTEGER,
	BAIRRO VARCHAR(40),
	CEP VARCHAR(15),
	CIDADE VARCHAR(60),
	ESTADO VARCHAR(40),
	ID_EMPRESA INTEGER,
	FG_ATIVO INTEGER,
 CONSTRAINT PK_TB_CLIENTE_JURIDICO_ID_CLIENTE PRIMARY KEY(ID_CLIENTE));

 CREATE TABLE TB_SERVICO(
	ID_SERVICO	SERIAL,
	DESCRICAO	VARCHAR(40),
	VALOR		NUMERIC(7,2),
	FG_ATIVO	INTEGER,
CONSTRAINT TB_SERVICO_ID_SERVICO PRIMARY KEY (ID_SERVICO));

INSERT INTO TB_CLIENTE_FISICO (ID_CLIENTE, NOME, SOBRENOME, CPF, DT_NASCIMENTO, EMAIL, TELEFONE, RUA, NUMERO, BAIRRO, CEP, CIDADE, ESTADO, ID_EMPRESA,	FG_ATIVO)
VALUES
(DEFAULT, 'MARCELO', 'ANDRADE', '44807756842', '26/12/1997', 'MARCELO@HOTMAIL.COM', '16992362117', 'JOãO MAURICIO DE SOUZA', 3893, 'SAMELLO WOODS', '14403734', 'FRANCA', 'SP', 1,1);

INSERT INTO TB_CLIENTE_JURIDICO (ID_CLIENTE, NOME_FANTASIA, RAZAO_SOCIAL, CNPJ, EMAIL, TELEFONE, RUA, NUMERO, BAIRRO, CEP, CIDADE, ESTADO, ID_EMPRESA, FG_ATIVO)
VALUES
(DEFAULT, 'Vida em Fios', 'Vida Comesticos & Cia', '78425986003615', 'studio@gmail.com', '16992123366', 'Eliza Verzola Gozuem', 4588, 'Prol. Angela Rosa', '14405765', 'Franca', 'SP', 1, 1);

INSERT INTO TB_EMPRESA(ID_EMPRESA, RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, EMAIL, SENHA, TELEFONE, RUA, NUMERO, BAIRRO, CEP, CIDADE, ESTADO, FG_ATIVO)
VALUES
(DEFAULT, 'Empresa Teste', 'Empresa Teste', '78592986093615', 'admin@admin.com', md5('admin'), '16992334455', 'Rua Andorinhas', 1235, 'Aeroporto', '14402323', 'Guara', 'MG', 1);

select * from TB_EMPRESA

INSERT INTO TB_CLIENTE_FISICO (ID_CLIENTE, NOME, SOBRENOME, CPF, DT_NASCIMENTO, EMAIL, TELEFONE, RUA, NUMERO, BAIRRO, CEP, CIDADE, ESTADO, ID_EMPRESA, FG_ATIVO) 
VALUES
(default, 'Vinicius', 'Mijoler', '123.321.456-78', '23/05/1998', 'vinicius@ernetwor.com.br', '(16)9 9999-5655', 'Morais Silva', 1234 , 'Finlandia', '14407-565', 'Acre', 'SP', 1, 1);

INSERT INTO TB_CLIENTE_JURIDICO (ID_CLIENTE, NOME_FANTASIA, RAZAO_SOCIAL, CNPJ, EMAIL, TELEFONE, RUA, NUMERO, BAIRRO, CEP, CIDADE, ESTADO, ID_EMPRESA, FG_ATIVO) 
VALUES(default, 'Refeições Oliveira', 'J A Refeições cia', '05.975.348/6245-26', 'jean@hotmail.com', '(16)3 2043-851', 'undefined', 1598 , 'Rivieira', '14405-789', 'Franca', 'SP', 1, 1);


INSERT INTO TB_EMPRESA(ID_EMPRESA, DESCRICAO, VALOR, FG_ATIVO) VALUES(default, 'Troca de Oleo', 400, 1);

Select * from TB_SERVICO


  